### ISSUE TITLE
ATOM/RSS doesn't self discover

### ISSUE THREAD

**Issue by dolanor** [jessfraz/weirdtrickmafia.fm#2]
Putting https://weirdtrickmafia.fm in my podcast app (podcast addict) didn't detect the atom/rss feed. So I had to read source code to get it.
I think there are some html meta tag to make it "standard". Don't remember, though.

**Comment by dolanor** [comment]
```
<link href="https://weirdtrickmafia.fm/post/index.xml" rel="alternate" title="Weird Trick Mafia Feed" type="application/rss+xml">
```
Should do it?

**Comment by dolanor** [comment]
I was on the pilot link, and there, the ATOM/RSS link wasn't there… Sorry.
And my podcast app didn't discover the link in the main page. I had to enter the URL manually.
Sorry.

**Comment by dolanor** [comment]
There is actually a problem. There are 2 RSS feeds advertised:
* `/index.xml`
* `/post/index.xml`

The first one has the list of both episodes but doesn't have the `<enclosure>` with the media in it, and the second one, only the episode that has the audio hosted locally.
Maybe for the first episode, some `/audio/fake.mp3` could redirect to the arrested devops mp3, or copy it in `/audio` and name it in the post params.

**Comment by jessfraz** [comment]
Ya one is for the blog aspect and one is for uploading to all the podcast services

**Comment by jessfraz** [comment]
I didn’t want the pilot to be added to the services since it’s not our podcast. Merely wanted to cross post it

**Comment by dolanor** [comment]
Ok, thanks for taking time to explain.
